---
- hosts: test
  connection: ssh
  tasks:
  - name: install java 
    yum : name=java-1.8.0-openjdk state=present
  - name: getting url from dlcdn.org.in 
    get_url:
      url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz"
      dest: "/root"
  - name: untar the file
    command: tar -zxvf apache-tomcat-9.0.83.tar.gz
  - name: rename the file
    command: mv apache-tomcat-9.0.83 tomcat
    tags: abc
  - name: change the tomcat-users 
    template:
      src: "context.xml"
      dest: "tomcat/webapps/manager/META-INF/context.xml"
  - name: change the configurations
    template:
      src: "tomcat-users.xml"
      dest: "tomcat/conf/tomcat-users.xml"
  - name: start the tomcat
    shell: nohup ./tomcat/bin/startup.sh
  - name: install web server
    action: yum name=httpd state=present
  - name: start webser
    service: name=httpd state=started


